backend:
  name: github
  repo: aampers/the-womens-war
media_folder: public/assets
public_folder: /assets
collections:
  - name: episode
    label: Episode
    folder: src/episodes
    create: true
    fields:
      - { name: "number", label: "Episode Number", widget: "number", valueType: "int" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "markdown", required: false }
      - { name: "pdf", label: "Script (PDF)", widget: "file", required: false }
      - { name: "epub", label: "Script (EPUB)", widget: "file", required: false }
      - { name: "link", label: "Link to the episode on iHeart", widget: "string", required: false }
      # - { name: date, label: Date, widget: datetime }